In [2]:
import pandas as pd

In [3]:
df1 = pd.read_csv("/Users/Sundipta/Desktop/180124_ty2_rox.csv")

In [4]:
df1 = df1.dropna()
df1

        Time       B1     B2      B3      B4      B5     B6     B7     B8
0    0:00:00  1142053  42550   44025   43035   44073  43839  43090  45052
1    0:01:00  1141145  42207   43682   43001   43689  43539  42846  45006
2    0:02:00  1138825  42099   43858   42916   43785  43551  42900  44959
3    0:03:00  1148986  42235   43605   42838   43760  43962  42945  44850
4    0:04:00  1147125  42310   43771   42769   43697  43536  42789  45062
5    0:05:00  1150965  42254   43780   43011   43835  43516  42792  44916
6    0:06:00  1145310  42217   43647   42769   43923  43553  42911  44647
7    0:07:00  1141533  42240   43818   43027   43975  43471  43060  44993
8    0:08:00  1145540  42368   43890   43078   43934  43426  42967  44910
9    0:09:00  1146105  42315   43845   42917   43932  43475  42910  45083
10   0:10:00  1149721  42328   43812   42926   43986  43582  43061  45038
11   0:00:00  1145752  42579  124116  159920  186784  44181  43774  45610
12   0:01:00  1150108  42546  124819  160987  188080  44882  44269  46294
13   0:02:00  1150521  42490  124300  161679  187782  45814  45301  47510
14   0:03:00  1145800  42290  125499  162921  187662  46351  45880  48265
15   0:04:00  1150493  42210  124811  162224  189240  47121  46668  49053
16   0:05:00  1146313  42353  125635  163592  189749  47635  47482  49398
17   0:06:00  1149012  42232  125047  162716  189237  47846  47761  50017
18   0:07:00  1147182  42252  125481  162656  188843  48340  48267  50096
19   0:08:00  1140903  42416  125750  162603  190587  48449  48495  50448
20   0:09:00  1147350  42297  124995  163580  189744  48657  48754  50458
21   0:10:00  1150844  42588  125469  164242  190823  48783  48946  50639
22   0:11:00  1152454  42468  126361  161359  189934  49032  48855  50961
23   0:12:00  1150454  42491  125944  161224  191447  49267  48979  51068
24   0:13:00  1150351  42530  125351  162503  189613  49038  49174  51032
25   0:14:00  1148063  42664  126463  163378  190946  49215  49263  51043
26   0:15:00  1149131  42641  125430  162891  190419  49243  49472  50879
27   0:16:00  1159660  42743  124566  163767  189983  49522  49533  51072
28   0:17:00  1154835  42647  126529  163010  190789  49451  49530  51324
29   0:18:00  1155424  42663  126421  163799  190320  49746  49467  51417
..       ...      ...    ...     ...     ...     ...    ...    ...    ...
107  1:15:00  1146612  43683  125438  162278  192569  51928  86667  87666
108  1:16:00  1157791  43839  125610  162019  190382  51869  86827  87563
109  1:17:00  1156680  43403  126107  163631  190793  51848  87182  87893
110  1:18:00  1153410  43559  125414  162185  190390  51777  87206  87985
111  1:19:00  1151156  43540  125252  162631  189864  51916  87248  87692
112  1:20:00  1156416  43759  125205  162629  191329  52191  87433  87674
113  1:21:00  1155777  43533  125947  162837  190700  51900  87167  87626
114  1:22:00  1152384  43742  124944  162768  190515  51785  87359  88063
115  1:23:00  1151550  43796  126028  163643  190768  51924  87641  88015
116  1:24:00  1153723  43770  125629  163989  189123  52085  87413  87659
117  1:25:00  1153013  43764  126149  163848  190920  52332  87208  87883
118  1:26:00  1153137  43762  125000  163630  189253  52060  87219  87877
119  1:27:00  1153199  43750  126088  163756  191406  52234  87162  88047
120  1:28:00  1156353  43898  125847  163324  190859  52388  87545  88112
121  1:29:00  1158830  43846  125915  162926  190172  52293  87521  88136
122  1:30:00  1161332  43701  125768  163896  188780  52279  87407  88272
123  1:31:00  1154705  43888  126706  163711  191720  52475  87312  88452
124  1:32:00  1153937  43785  125684  163372  191197  52202  87213  88178
125  1:33:00  1156224  43775  125139  164014  192042  52147  87404  88096
126  1:34:00  1159965  44033  125139  163536  191251  52106  87683  88317
127  1:35:00  1152769  43885  125147  162835  190172  52368  87727  88362
128  1:36:00  1157795  43885  126104  163652  189950  52320  87496  88533
129  1:37:00  1152706  43972  125906  163190  191383  52479  87190  88389
130  1:38:00  1158151  43970  127011  163101  190399  52326  87935  88343
131  1:39:00  1160287  43884  126029  163797  191265  52537  87443  88008
132  1:40:00  1160010  43950  125914  163112  191585  52570  87526  88361
133  1:41:00  1156380  43989  125430  163540  192823  52625  87702  88116
134  1:42:00  1156920  44081  126188  163713  191194  52778  87726  88229
135  1:43:00  1154833  44210  126000  164026  190739  52678  87714  88466
136  1:44:00  1160921  43942  126686  164126  191339  52580  87613  88466

[137 rows x 9 columns]

In [5]:
import dateutil

start = dateutil.parser.parse('2018-01-24 00:00:00')

In [6]:
time = df1['Time']
t1 = pd.to_datetime(time).iloc[2]
(t1 - start).total_seconds()

172920.0

In [7]:
import datetime
import time

In [8]:
#x = time.strptime('05:12:01','%H:%M:%S')
#datetime.timedelta(hours=x.tm_hour,minutes=x.tm_min,seconds=x.tm_sec).total_seconds()

In [9]:
new_data = []
for idx, time_str in df1["Time"].iteritems():
    x = time.strptime(time_str,'%H:%M:%S')
    secs = datetime.timedelta(hours=x.tm_hour,minutes=x.tm_min,seconds=x.tm_sec).total_seconds() 
    new_data.append(secs)
df1["Time_secs"] = new_data

In [10]:
df1.head(50)

,Time,B1,B2,B3,B4,B5,B6,B7,B8,Time_secs
0,0:00:00,1142053,42550,44025,43035,44073,43839,43090,45052,0.0
1,0:01:00,1141145,42207,43682,43001,43689,43539,42846,45006,60.0
2,0:02:00,1138825,42099,43858,42916,43785,43551,42900,44959,120.0
3,0:03:00,1148986,42235,43605,42838,43760,43962,42945,44850,180.0
4,0:04:00,1147125,42310,43771,42769,43697,43536,42789,45062,240.0
5,0:05:00,1150965,42254,43780,43011,43835,43516,42792,44916,300.0
6,0:06:00,1145310,42217,43647,42769,43923,43553,42911,44647,360.0
7,0:07:00,1141533,42240,43818,43027,43975,43471,43060,44993,420.0
8,0:08:00,1145540,42368,43890,43078,43934,43426,42967,44910,480.0
9,0:09:00,1146105,42315,43845,42917,43932,43475,42910,45083,540.0
10,0:10:00,1149721,42328,43812,42926,43986,43582,43061,45038,600.0
11,0:00:00,1145752,42579,124116,159920,186784,44181,43774,45610,0.0
12,0:01:00,1150108,42546,124819,160987,188080,44882,44269,46294,60.0
13,0:02:00,1150521,42490,124300,161679,187782,45814,45301,47510,120.0
14,0:03:00,1145800,42290,125499,162921,187662,46351,45880,48265,180.0
15,0:04:00,1150493,42210,124811,162224,189240,47121,46668,49053,240.0
16,0:05:00,1146313,42353,125635,163592,189749,47635,47482,49398,300.0
17,0:06:00,1149012,42232,125047,162716,189237,47846,47761,50017,360.0
18,0:07:00,1147182,42252,125481,162656,188843,48340,48267,50096,420.0
19,0:08:00,1140903,42416,125750,162603,190587,48449,48495,50448,480.0
20,0:09:00,1147350,42297,124995,163580,189744,48657,48754,50458,540.0
21,0:10:00,1150844,42588,125469,164242,190823,48783,48946,50639,600.0
22,0:11:00,1152454,42468,126361,161359,189934,49032,48855,50961,660.0
23,0:12:00,1150454,42491,125944,161224,191447,49267,48979,51068,720.0
24,0:13:00,1150351,42530,125351,162503,189613,49038,49174,51032,780.0
25,0:14:00,1148063,42664,126463,163378,190946,49215,49263,51043,840.0
26,0:15:00,1149131,42641,125430,162891,190419,49243,49472,50879,900.0
27,0:16:00,1159660,42743,124566,163767,189983,49522,49533,51072,960.0
28,0:17:00,1154835,42647,126529,163010,190789,49451,49530,51324,1020.0
29,0:18:00,1155424,42663,126421,163799,190320,49746,49467,51417,1080.0
30,0:19:00,1158703,42571,126597,162767,190587,49502,49447,51529,1140.0
31,0:20:00,1153725,42513,125286,162782,190384,49778,49429,51518,1200.0
32,0:00:00,1154747,42991,125379,162788,191988,49929,50653,52555,0.0
33,0:01:00,1153373,42937,124671,162837,190296,49873,50773,52648,60.0
34,0:02:00,1149212,42622,125584,162608,188989,49717,52073,54506,120.0
35,0:03:00,1154878,42912,124653,162678,190913,50091,55866,58043,180.0
36,0:04:00,1155708,42620,124614,162706,189972,49795,60507,63278,240.0
37,0:05:00,1160032,42645,124551,163320,191001,49906,65970,68658,300.0
38,0:06:00,1154673,42806,126034,163062,190999,50091,70388,73485,360.0
39,0:07:00,1154975,42622,125786,163334,191396,50080,74849,77633,420.0
40,0:08:00,1153543,42674,125439,162001,191321,50068,77709,80198,480.0
41,0:09:00,1153912,42790,125575,162745,190375,50146,80179,82018,540.0
42,0:10:00,1151143,42854,124110,163530,190363,49927,81469,83507,600.0
43,0:11:00,1149666,42697,125090,163023,190531,50190,82609,83930,660.0
44,0:12:00,1156034,42658,125588,163449,190912,50346,83362,84698,720.0
45,0:13:00,1153880,42874,126133,162579,190518,50211,83608,85162,780.0
46,0:14:00,1154054,42881,124844,163680,189800,50365,83981,85031,840.0
47,0:15:00,1153325,42917,125029,162827,191290,50368,84205,85167,900.0
48,0:16:00,1155046,42682,125274,163434,188697,50641,84541,85356,960.0
49,0:17:00,1156106,42901,125408,163152,191323,50473,84362,85388,1020.0

In [11]:
row_numbers = list(df1[df1["Time_secs"] == 0].iloc[1:].index)
offsets = [0,0]
def fix_Time(row_numbers, offsets, dataframe):
    if len(row_numbers) != len(offsets):
        raise Exception("Fix your vectors")
    
    copy = dataframe.copy()
    
    for row_number, offset in zip(row_numbers, offsets):
        last = int(row_number) - 1
        to_add = dataframe.loc[last]['Time_secs'] + offset
        print to_add
        copy.loc[dataframe[dataframe.index >= row_number].index, 'Time_secs'] += to_add
    
    return copy

df2 = fix_Time(row_numbers, offsets, df1)
df2[df2["Time_secs"]== 0]

600.0
1200.0

,Time,B1,B2,B3,B4,B5,B6,B7,B8,Time_secs
0,0:00:00,1142053,42550,44025,43035,44073,43839,43090,45052,0.0

In [12]:
df2.to_csv('180124_ty2_processed.csv')
#df2.to_csv('170129_T1_rep3_processed.tsv', sep = '\t')

In [153]:
df2.head(50)

,Time,B1,B2,B3,B4,B5,B6,B7,B8,Time_secs
0,0:00:00,1142053,42550,44025,43035,44073,43839,43090,45052,0.0
1,0:01:00,1141145,42207,43682,43001,43689,43539,42846,45006,60.0
2,0:02:00,1138825,42099,43858,42916,43785,43551,42900,44959,120.0
3,0:03:00,1148986,42235,43605,42838,43760,43962,42945,44850,180.0
4,0:04:00,1147125,42310,43771,42769,43697,43536,42789,45062,240.0
5,0:05:00,1150965,42254,43780,43011,43835,43516,42792,44916,300.0
6,0:06:00,1145310,42217,43647,42769,43923,43553,42911,44647,360.0
7,0:07:00,1141533,42240,43818,43027,43975,43471,43060,44993,420.0
8,0:08:00,1145540,42368,43890,43078,43934,43426,42967,44910,480.0
9,0:09:00,1146105,42315,43845,42917,43932,43475,42910,45083,540.0
10,0:10:00,1149721,42328,43812,42926,43986,43582,43061,45038,600.0
11,0:00:00,1145752,42579,124116,159920,186784,44181,43774,45610,600.0
12,0:01:00,1150108,42546,124819,160987,188080,44882,44269,46294,660.0
13,0:02:00,1150521,42490,124300,161679,187782,45814,45301,47510,720.0
14,0:03:00,1145800,42290,125499,162921,187662,46351,45880,48265,780.0
15,0:04:00,1150493,42210,124811,162224,189240,47121,46668,49053,840.0
16,0:05:00,1146313,42353,125635,163592,189749,47635,47482,49398,900.0
17,0:06:00,1149012,42232,125047,162716,189237,47846,47761,50017,960.0
18,0:07:00,1147182,42252,125481,162656,188843,48340,48267,50096,1020.0
19,0:08:00,1140903,42416,125750,162603,190587,48449,48495,50448,1080.0
20,0:09:00,1147350,42297,124995,163580,189744,48657,48754,50458,1140.0
21,0:10:00,1150844,42588,125469,164242,190823,48783,48946,50639,1200.0
22,0:11:00,1152454,42468,126361,161359,189934,49032,48855,50961,1260.0
23,0:12:00,1150454,42491,125944,161224,191447,49267,48979,51068,1320.0
24,0:13:00,1150351,42530,125351,162503,189613,49038,49174,51032,1380.0
25,0:14:00,1148063,42664,126463,163378,190946,49215,49263,51043,1440.0
26,0:15:00,1149131,42641,125430,162891,190419,49243,49472,50879,1500.0
27,0:16:00,1159660,42743,124566,163767,189983,49522,49533,51072,1560.0
28,0:17:00,1154835,42647,126529,163010,190789,49451,49530,51324,1620.0
29,0:18:00,1155424,42663,126421,163799,190320,49746,49467,51417,1680.0
30,0:19:00,1158703,42571,126597,162767,190587,49502,49447,51529,1740.0
31,0:20:00,1153725,42513,125286,162782,190384,49778,49429,51518,1800.0
32,0:00:00,1154747,42991,125379,162788,191988,49929,50653,52555,1800.0
33,0:01:00,1153373,42937,124671,162837,190296,49873,50773,52648,1860.0
34,0:02:00,1149212,42622,125584,162608,188989,49717,52073,54506,1920.0
35,0:03:00,1154878,42912,124653,162678,190913,50091,55866,58043,1980.0
36,0:04:00,1155708,42620,124614,162706,189972,49795,60507,63278,2040.0
37,0:05:00,1160032,42645,124551,163320,191001,49906,65970,68658,2100.0
38,0:06:00,1154673,42806,126034,163062,190999,50091,70388,73485,2160.0
39,0:07:00,1154975,42622,125786,163334,191396,50080,74849,77633,2220.0
40,0:08:00,1153543,42674,125439,162001,191321,50068,77709,80198,2280.0
41,0:09:00,1153912,42790,125575,162745,190375,50146,80179,82018,2340.0
42,0:10:00,1151143,42854,124110,163530,190363,49927,81469,83507,2400.0
43,0:11:00,1149666,42697,125090,163023,190531,50190,82609,83930,2460.0
44,0:12:00,1156034,42658,125588,163449,190912,50346,83362,84698,2520.0
45,0:13:00,1153880,42874,126133,162579,190518,50211,83608,85162,2580.0
46,0:14:00,1154054,42881,124844,163680,189800,50365,83981,85031,2640.0
47,0:15:00,1153325,42917,125029,162827,191290,50368,84205,85167,2700.0
48,0:16:00,1155046,42682,125274,163434,188697,50641,84541,85356,2760.0
49,0:17:00,1156106,42901,125408,163152,191323,50473,84362,85388,2820.0